version: 3.4

networks:
    api-dev:
        driver: bridge


services:
    api: api:latest
    depends_on:
        - "db"
    build:
        contexr: .
        dockerfile: dockerfile
    ports:
        - "5000"
    environment:
        DB_CONECTION_STRING: "host=db;port=5432;database=svc;username=postgres;password=password"
    networks:
        - api-dev

db:
    image: postgres:latest
    ports:
        - "5432"
    restart: always
    voulumes:
        - db_volume:/var/lib/postgresql/data
        - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "password"
        POSTGRES_DB: "svc"
    networks:
        - api-dev

volumes:
    db_volume: