version: "3.4"

services:
    api: 
        image: api:latest
        depends_on:
            - "db"
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
        networks:
            - api-dev

    db:
        image: postgres:latest
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - ./dbscripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql
            - ./db_volume:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "password"
            POSTGRES_DB: "svc"
        networks:
            - api-dev

volumes:
    db_volume:

networks:
    api-dev:
        driver: bridge